-- QUERY DE LOS MEDICOS + ESPECIALIDADES
SELECT M.ID_MEDICO AS ID, ID_USUARIO, NOMBRE, APELLIDO TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO, E.TIPO AS ESPECIALIDAD
FROM MEDICOS M
INNER JOIN MEDICOSXESPECIALIDAD ME ON ME.ID_MEDICO = M.ID_MEDICO
INNER JOIN ESPECIALIDADES E ON E.ID_ESPECIALIDAD = ME.ID_ESPECIALIDAD

-- QUERY DE LOS PACIENTES
SELECT ID_PACIENTE, ID_USUARIO, NOMBRE, APELLIDO, TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO
FROM PACIENTES P
SELECT * FROM PACIENTES

-- QUERY DE LAS OBSERVACIONES
SELECT ID_OBSERVACION, ID_TURNO, OBSERVACION FROM OBSERVACIONES

-- QUERY DE LOS TURNOS CON NOMBRES DE PACIENTES Y MEDICOS
SELECT ID_TURNO, M.ID_MEDICO , M.NOMBRE AS MNOMBRE, P.NOMBRE AS PNOMBRE, FECHA, HORA_INICIO, HORA_FIN, T.ESTADO AS ESTADO 
FROM TURNOS T 
INNER JOIN MEDICOS M ON M.ID_MEDICO = T.ID_MEDICO 
INNER JOIN PACIENTES P ON P.ID_PACIENTE = T.ID_PACIENTE

-- QUERY DE LOS USUARIOS
SELECT ID_USUARIO, NOMBRE_USUARIO, CONTRASENA, TIPO FROM USUARIOS

--QUERY DE LOS TURNOS X MEDICO
SELECT * FROM TURNOS WHERE @ID_MEDICO = ID_MEDICO

-- ELIMINAR BASE DE DATOS
DROP DATABASE CLINICA

-- CREACION DE LA BASE DE DATOS
CREATE DATABASE CLINICA
GO
USE CLINICA
GO

-- CREACION DE TABLAS
CREATE TABLE ESPECIALIDADES (
    ID_ESPECIALIDAD TINYINT NOT NULL PRIMARY KEY IDENTITY(1,1),
    TIPO VARCHAR(20) NOT NULL
)
GO
CREATE TABLE USUARIOS (
    ID_USUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOMBRE_USUARIO VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(30) NOT NULL,
    TIPO VARCHAR(20) NOT NULL CHECK (TIPO IN ('Administrador', 'Recepcionista', 'Médico', 'Paciente'))
)
GO
CREATE TABLE PACIENTES (
    ID_PACIENTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_USUARIO INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL CHECK(FECHA_NACIMIENTO <= GETDATE()),
    MAIL VARCHAR(100) NOT NULL,
    ESTADO BIT DEFAULT(1) NOT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
)
GO
CREATE TABLE MEDICOS (
    ID_MEDICO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_USUARIO INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL CHECK(FECHA_NACIMIENTO <= GETDATE()),
    MAIL VARCHAR(100) NOT NULL,
    ESTADO BIT DEFAULT(1),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
)
GO
CREATE TABLE TURNOS (
    ID_TURNO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_MEDICO INT NOT NULL,
	ID_PACIENTE INT NOT NULL,
    FECHA DATE NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    ESTADO VARCHAR(30) CHECK (ESTADO IN ('Activo', 'Reprogramado', 'Cancelado', 'No asistió', 'Finalizado')),
	FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO),
	FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
)
GO
CREATE TABLE OBSERVACIONES (
    ID_OBSERVACION INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_TURNO INT NOT NULL,
    OBSERVACION VARCHAR(1500) NOT NULL,
	FOREIGN KEY (ID_TURNO) REFERENCES TURNOS(ID_TURNO)
)
GO
CREATE TABLE MEDICOSXESPECIALIDAD(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_MEDICO INT NOT NULL,
	ID_ESPECIALIDAD TINYINT NOT NULL,
	FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO),
	FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDADES(ID_ESPECIALIDAD)
)
GO

--CREATE TABLE HORARIOSXMEDICO(
--	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
--	ID_MEDICO INT NOT NULL,
--	HORARIO_ENTRADA TIME NOT NULL,
--	HORARIO_SALIDA TIME NOT NULL,
--	FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
--)

-- INSERTS CON INFORMACIÓN PARA CADA TABLA
INSERT INTO ESPECIALIDADES (TIPO) 
VALUES ('Cardiología'),
       ('Dermatología'),
       ('Gastroenterología'),
       ('Oftalmología');


-- USUARIOS
INSERT INTO USUARIOS (NOMBRE_USUARIO, CONTRASENA, TIPO) 
VALUES ('paciente1', 'contrasena1', 'Paciente'),
       ('paciente2', 'contrasena2', 'Paciente'),
       ('paciente3', 'contrasena3', 'Paciente'),
       ('paciente4', 'contrasena4', 'Paciente'),
	   ('medico1', 'contrasena1', 'Médico'),
       ('medico2', 'contrasena2', 'Médico'),
       ('medico3', 'contrasena3', 'Médico'),
       ('medico4', 'contrasena4', 'Médico'),
	   ('Admin', '123', 'Administrador'),
	   ('Recepcionista', '123', 'Recepcionista');

INSERT INTO PACIENTES (ID_USUARIO, NOMBRE, APELLIDO, TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO)
VALUES (1, 'Paciente1', 'Apellido1', '1234567891', 'Dirección1', '1990-01-01', 'paciente1@mail.com', 1),
       (2, 'Paciente2', 'Apellido2', '1234567892', 'Dirección2', '1990-02-02', 'paciente2@mail.com', 1),
       (3, 'Paciente3', 'Apellido3', '1234567893', 'Dirección3', '1990-03-03', 'paciente3@mail.com', 1),
       (4, 'Paciente4', 'Apellido4', '1234567894', 'Dirección4', '1990-04-04', 'paciente4@mail.com', 1);

INSERT INTO MEDICOS (ID_USUARIO, NOMBRE, APELLIDO, TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO)
VALUES (5, 'Médico1', 'Apellido1', '9876543211', 'Dirección1', '1980-01-01', 'medico1@mail.com', 1),
       (6, 'Médico2', 'Apellido2', '9876543212', 'Dirección2', '1980-02-02', 'medico2@mail.com', 1),
       (7, 'Médico3', 'Apellido3', '9876543213', 'Dirección3', '1980-03-03', 'medico3@mail.com', 1),
       (8, 'Médico4', 'Apellido4', '9876543214', 'Dirección4', '1980-04-04', 'medico4@mail.com', 1);

INSERT INTO TURNOS (ID_MEDICO, ID_PACIENTE, FECHA, HORA_INICIO, HORA_FIN, ESTADO)
VALUES (1, 1, '2023-11-01', '09:00:00', '10:00:00', 'Activo'),
       (2, 1, '2023-11-02', '10:00:00', '11:00:00', 'Activo'),
       (3, 3, '2023-11-03', '11:00:00', '12:00:00', 'Activo'),
       (3, 4, '2023-11-04', '12:00:00', '13:00:00', 'Activo'),
	   (4, 4, '2023-11-04', '12:00:00', '13:00:00', 'Activo');

INSERT INTO OBSERVACIONES (ID_TURNO, OBSERVACION)
VALUES
    (1,'El paciente presentó mejoras significativas.'),
    (2,'Continuar con el tratamiento actual.'),
    (3,'Se recomienda una cirugía para resolver el problema.'),
    (4,'Se espera una recuperación completa en unas semanas.');

INSERT INTO MEDICOSXESPECIALIDAD (ID_MEDICO, ID_ESPECIALIDAD)
VALUES (1, 1),
  	   (1, 2),
       (2, 2),
       (3, 3),
       (4, 4);


