-- QUERY DE LOS MEDICOS + ESPECIALIDADES
SELECT ID_MEDICO, NOMBRE, TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO, M.ID_ESPECIALIDAD as ESPECIALIDAD, E.TIPO as TIPO 
FROM MEDICOS M 
INNER JOIN ESPECIALIDADES E ON M.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD

-- QUERY DE LOS PACIENTES + OBSERVACIONES
SELECT P.ID_PACIENTE AS PCIENTE, NOMBRE, APELLIDO, TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO, O.OBSERVACION AS OBS, o.ID_MEDICO as MEDICO, o.FECHA as FECHA 
FROM PACIENTES P 
LEFT JOIN OBSERVACIONES O ON P.ID_PACIENTE = O.ID_PACIENTE

-- QUERY DE LOS TURNOS CON NOMBRES DE PACIENTES Y MEDICOS
SELECT ID_TURNO, M.ID_MEDICO , M.NOMBRE AS MNOMBRE, P.NOMBRE AS PNOMBRE, FECHA, HORA_INICIO, HORA_FIN, T.ESTADO AS ESTADO 
FROM TURNOS T 
INNER JOIN MEDICOS M ON M.ID_MEDICO = T.ID_MEDICO 
INNER JOIN PACIENTES P ON P.ID_PACIENTE = T.ID_PACIENTE

-- QUERY DE LOS USUARIOS
SELECT ID_USUARIO, NOMBRE_USUARIO, CONTRASENA, TIPO FROM USUARIOS

-- INSERT PARA REGISTRAR UN USUARIO
INSERT INTO USUARIOS (NOMBRE_USUARIO, CONTRASENA, TIPO) VALUES('Facu', 'San', 'Médico')

-- ELIMINAR BASE DE DATOS
DROP DATABASE CLINICA

-- CREACION DE LA BASE DE DATOS
CREATE DATABASE CLINICA
GO
USE CLINICA
GO

-- CREACION DE TABLAS 
CREATE TABLE ESPECIALIDADES (
    ID_ESPECIALIDAD TINYINT NOT NULL PRIMARY KEY IDENTITY(1,1),
    TIPO VARCHAR(100) NOT NULL
)
GO

CREATE TABLE PACIENTES (
    ID_PACIENTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL CHECK(FECHA_NACIMIENTO <= GETDATE()),
    MAIL VARCHAR(100) NOT NULL,
    ESTADO BIT DEFAULT(1) NOT NULL
)
GO

CREATE TABLE MEDICOS (
    ID_MEDICO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL CHECK(FECHA_NACIMIENTO <= GETDATE()),
    MAIL VARCHAR(100) NOT NULL,
    ESTADO BIT DEFAULT(1),
	ID_ESPECIALIDAD TINYINT NOT NULL,
    FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDADES(ID_ESPECIALIDAD)
)
GO

CREATE TABLE TURNOS (
    ID_TURNO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_MEDICO INT NOT NULL,
	ID_PACIENTE INT NOT NULL,
    FECHA DATETIME NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    ESTADO BIT DEFAULT(1)
	FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO),
	FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
)
GO

CREATE TABLE USUARIOS (
    ID_USUARIO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOMBRE_USUARIO VARCHAR(50) NOT NULL,
    CONTRASENA VARCHAR(50) NOT NULL,
    TIPO VARCHAR(20) NOT NULL CHECK (TIPO IN ('Administrador', 'Recepcionista', 'Médico'))
)
GO
CREATE TABLE OBSERVACIONES (
    ID_OBSERVACION INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    OBSERVACION VARCHAR(500) NOT NULL,
	FECHA DATETIME NOT NULL,
    ID_MEDICO INT NOT NULL,
    ID_PACIENTE INT NOT NULL
	FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO),
	FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
)
GO

-- INSERTS CON INFORMACIÓN PARA CADA TABLA 

INSERT INTO ESPECIALIDADES (TIPO)
VALUES
    ('Cardiología'),
    ('Dermatología'),
    ('Oftalmología'),
    ('Pediatría'),
    ('Ginecología'),
    ('Ortopedia');

INSERT INTO PACIENTES (NOMBRE, APELLIDO, TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO)
VALUES
    ('Juan', 'Pérez', '123-456-7890', 'Calle 123', '1990-05-15', 'juan@email.com', 1),
    ('María', 'González', '987-654-3210', 'Avenida 456', '1985-02-20', 'maria@email.com', 1),
    ('Luis', 'Rodríguez', '555-555-5555', 'Calle 789', '1992-10-10', 'luis@email.com', 1),
    ('Ana', 'Sánchez', '444-333-2222', 'Avenida 987', '1980-08-05', 'ana@email.com', 1),
    ('Roberto', 'López', '777-888-9999', 'Calle 567', '1975-12-25', 'roberto@email.com', 1),
    ('Elena', 'Martínez', '666-111-2222', 'Avenida 321', '1995-04-30', 'elena@email.com', 1);

INSERT INTO MEDICOS (NOMBRE, TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO, ID_ESPECIALIDAD)
VALUES
    ('Dr. García', '111-222-3333', 'Calle Médica 1', '1970-03-10', 'garcia@email.com', 1, 1),
    ('Dra. Rodríguez', '444-555-6666', 'Avenida Salud 2', '1982-08-15', 'rodriguez@email.com', 1, 2),
    ('Dr. López', '777-888-9999', 'Calle Sanar 3', '1990-05-20', 'lopez@email.com', 1, 1),
    ('Dra. Pérez', '555-555-5555', 'Avenida Curar 4', '1985-12-30', 'perez@email.com', 1, 3),
    ('Dr. Martínez', '222-333-4444', 'Calle Salvar 5', '1978-04-25', 'martinez@email.com', 1, 4),
    ('Dra. Sánchez', '666-777-8888', 'Avenida Saludable 6', '1995-06-10', 'sanchez@email.com', 1, 5);

INSERT INTO TURNOS (ID_MEDICO, ID_PACIENTE, FECHA, HORA_INICIO, HORA_FIN, ESTADO)
VALUES
    (1, 1, '2023-10-24', '10:00:00', '11:00:00', 1),
    (1, 2, '2023-10-25', '14:30:00', '15:30:00', 1),
    (3, 3, '2023-10-26', '11:15:00', '12:15:00', 1),
    (4, 3, '2023-10-27', '09:45:00', '10:45:00', 1),
    (5, 5, '2023-10-28', '16:00:00', '17:00:00', 1),
    (6, 6, '2023-10-29', '12:30:00', '13:30:00', 1);

INSERT INTO USUARIOS (NOMBRE_USUARIO, CONTRASENA, TIPO)
VALUES
    ('admin1', 'contrasena1', 'Administrador'),
    ('admin2', 'contrasena2', 'Administrador'),
    ('recepcionista1', 'contrasena3', 'Recepcionista'),
    ('recepcionista2', 'contrasena4', 'Recepcionista'),
    ('medico1', 'contrasena5', 'Médico'),
    ('medico2', 'contrasena6', 'Médico');

-- Inserción en la tabla OBSERVACIONES
INSERT INTO OBSERVACIONES (OBSERVACION, FECHA, ID_MEDICO, ID_PACIENTE)
VALUES
    ('Paciente con fiebre alta.', '2023-10-24 10:30:00', 1, 1),
    ('Examen dermatológico completo.', '2023-10-25 15:45:00', 2, 2),
    ('Revisión de fractura en la pierna derecha.', '2023-10-26 11:30:00', 3, 3),
    ('Control ginecológico de rutina.', '2023-10-27 09:50:00', 4, 4),
    ('Consulta pediátrica de seguimiento.', '2023-10-28 16:15:00', 5, 5),
    ('Limpieza dental y revisión bucal.', '2023-10-29 12:45:00', 6, 6);
