USE CLINICA
GO
-- QUERY DE LAS ESPECIALIDADES
	SELECT ID_ESPECIALIDAD, TIPO FROM ESPECIALIDADES

-- QUERY DE LOS USUARIOS
	SELECT 
		ID_USUARIO, 
		NOMBRE_USUARIO, 
		CONTRASENA, 
		TIPO,
		URL_IMAGEN, 
		ESTADO
	FROM USUARIOS U 
	LEFT JOIN IMAGENES I ON I.ID_IMAGEN = U.ID_IMAGEN


-- QUERY DE LOS TURNOS
	SELECT 
		T.ID_TURNO AS IDTURNO,
		T.ID_MEDICO AS IDMEDICO,
		T.ID_PACIENTE AS IDPACIENTE,
		T.ID_HORARIO AS IDHORARIO,
		T.ID_ESPECIALIDAD AS IDESPECIALIDAD, 
		T.FECHA AS FECHA,
		H.HORA AS HORA,
		P.DNI AS DNIPACIENTE,
		T.ESTADO AS ESTADO,
		M.NOMBRE AS MNOMBRE,
		M.APELLIDO AS MAPELLIDO,
		P.NOMBRE AS PNOMBRE,
		P.APELLIDO AS PAPELLIDO,
		T.OBS_PACIENTE AS OBSERVACION_PACIENTE,
		T.OBS_MEDICO AS OBSERVACION_MEDICO 
	FROM TURNOS T 
	INNER JOIN MEDICOS M ON M.ID_MEDICO = T.ID_MEDICO 
	INNER JOIN PACIENTES P ON P.ID_PACIENTE = T.ID_PACIENTE 
	INNER JOIN HORARIOS H ON H.ID_HORARIO = T.ID_HORARIO

-- QUERY DE LOS PACIENTES
	SELECT ID_PACIENTE, ID_USUARIO, DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION, FECHA_NACIMIENTO, MAIL, ESTADO FROM PACIENTES

-- QUERY DE LOS MEDICOS
	SELECT 
        M.ID_MEDICO AS ID, 
        U.ID_USUARIO AS IDUSUARIO,
        M.DNI AS DNI,
        M.NOMBRE AS NOMBRE, 
        M.APELLIDO AS APELLIDO, 
        M.TELEFONO AS TELEFONO, 
        M.DIRECCION AS DIRECCION, 
        M.FECHA_NACIMIENTO AS FECHANACIMIENTO, 
        MAIL, M.ESTADO AS ESTADO,
        E.ID_ESPECIALIDAD AS IDESPECIALIDAD, 
        E.TIPO AS ESPECIALIDAD,
		MJ.ID_JORNADA AS IDJORNADA,
        J.TIPO_JORNADA AS JORNADA,
        I.URL_IMAGEN AS URL_IMAGEN
    FROM MEDICOS M 
    LEFT JOIN MEDICOSXESPECIALIDAD ME ON ME.ID_MEDICO = M.ID_MEDICO 
    LEFT JOIN ESPECIALIDADES E ON E.ID_ESPECIALIDAD = ME.ID_ESPECIALIDAD
    LEFT JOIN MEDICOXJORNADA MJ ON MJ.ID_MEDICO = M.ID_MEDICO
	INNER JOIN JORNADAS J ON J.ID_JORNADA = MJ.ID_JORNADA
    INNER JOIN USUARIOS U ON U.ID_USUARIO = M.ID_USUARIO 
    LEFT JOIN IMAGENES I ON I.ID_IMAGEN = U.ID_IMAGEN

-- QUERY DE LOS HORARIOS
	SELECT ID_HORARIO, HORA, DISPONIBILIDAD FROM HORARIOS

-- QUERY DE LOS HORARIOS EN UN DÍA ESPECÍFICO DE UN MÉDICO
	DECLARE @IDMedico INT = 1
	DECLARE @FechaConsulta DATE = '2023-12-06'
	DECLARE @HORA TIME = '09:00'
-- QUERY EN RESERVATURNO / EDITARTURNO
SELECT
	H.ID_HORARIO AS IDHORARIO, 
	H.HORA AS HORA,
	ISNULL(T.ID_TURNO, 0) AS IDTURNO,
	@IDMedico AS IDMEDICO,
	ISNULL(T.ESTADO, 'Disponible') AS ESTADO
FROM  
	HORARIOS H
JOIN
	MEDICOXJORNADA MJ ON H.ID_JORNADA = MJ.ID_JORNADA AND MJ.ID_MEDICO = @IDMedico
LEFT JOIN  
	TURNOS T ON H.ID_HORARIO = T.ID_HORARIO AND T.FECHA = @FechaConsulta AND T.ID_MEDICO = @IDMedico
WHERE T.ESTADO IS  NULL AND H.HORA >= @HORA
ORDER BY  H.HORA

-- INSERT DE UN TURNO
	INSERT INTO TURNOS (ID_MEDICO, ID_PACIENTE, ID_HORARIO, FECHA, ESTADO) VALUES(@IDMEDICO, @IDPACIENTE, @IDHORA, @FECHA, @ESTADO)

-- INSERT DE UNA IMAGEN
	INSERT INTO IMAGENES(URL_IMAGEN) VALUES (@URL)
	UPDATE USUARIOS SET ID_IMAGEN = (SELECT MAX(ID_IMAGEN) FROM IMAGENES) WHERE ID_USUARIO = @IDUSUARIO

--MODIFICAR JORNADAS
INSERT INTO MEDICOXJORNADA (ID_JORNADA, ID_MEDICO) VALUES (@IDJORNADA, @IDMedico) 


-- LÓGICA DE CANCELAR UN TURNO
-- 1) TOMAR UN TURNO

-- 2) GUARDAR ESE TURNO EN OTRA TABLA (EJEMPLO AL CANCELAR) Y CAMBIARLE EL ESTADO A 'CANCELADO'
-- INSERT DE CANCELADOS
INSERT INTO TURNOS_CANCELADOS (ID_TURNO, ID_MEDICO, ID_PACIENTE, ID_HORARIO, ID_ESPECIALIDAD, FECHA, ESTADO, OBS_MEDICO, OBS_PACIENTE)
VALUES(@IDTURNO, @IDMEDICO, @IDPACIENTE, @IDHORARIO, @IDESPECIALIDAD, @FECHA, 'Cancelado', @OBSMEDICO, @OBSPACIENTE)

-- 3) ELIMINAR EL TURNO DE LA TABLA TURNOS
DELETE FROM TURNOS WHERE ID_TURNO = @IDTURNO


-- INSERT DE REASIGNADOS
INSERT INTO TURNOS_Reagendados
(ID_TURNO, ID_MEDICO_ANTERIOR , ID_PACIENTE, ID_HORARIO_ANTERIOR, ID_ESPECIALIDAD, FECHA_ANTERIOR, ID_HORARIO_NUEVO, FECHA_NUEVA , ESTADO, OBS_PACIENTE)
VALUES(@IDTURNO, @IDMEDICOANTERIOR, @IDPACIENTE, @IDHORARIOANTERIOR, @IDESPECIALIDAD, @FECHAANTERIOR, @IDHORARIONUEVO, @FECHANUEVA ,'Reasignado',  @OBSPACIENTE)
